_id: 6596903fd71b6e002cfe32a4
name: 📄 pageTriggers
language: javascript
timeout: 12
triggers:
  onProjectsDataChange:
    type: bucket
    active: true
    options:
      bucket: 651e842a82063a002c6fa24f
      type: ALL
  onContractsDataChange:
    options:
      bucket: 65721d81d71b6e002cfaba28
      type: ALL
    type: bucket
    active: true
  changeOfferStandbyTime:
    options:
      timezone: UTC
      frequency: 0 0 * * *
    type: schedule
    active: true
  onProgressPaymentsDataChange:
    options:
      bucket: 65782dabd71b6e002cfb5489
      type: ALL
    type: bucket
    active: true
  onMonthlyProgressPaymentsDataChange:
    options:
      bucket: 657ae033d71b6e002cfbe32f
      type: ALL
    type: bucket
    active: true
  onGanttChartDataChange:
    options:
      bucket: 65489afcd71b6e002cf7406c
      type: INSERT
    type: bucket
    active: true
  changeEmployeesEveryDay:
    options:
      timezone: UTC
      frequency: 0 4 * * *
    type: schedule
    active: true
  changeEmployeesEveryYear:
    options:
      timezone: UTC
      frequency: 0 0 1 1 *
    type: schedule
    active: true
  onAnnualLeaveDataChange:
    options:
      bucket: 655f3140d71b6e002cf91f0b
      type: ALL
    type: bucket
    active: true
  onOvertimeDataChange:
    options:
      bucket: 655f5ee3d71b6e002cf94752
      type: ALL
    type: bucket
    active: true
env: {}
memoryLimit: 100
order: 5
