_id: 66b5f0d1e6d086002c5ddaee
title: PRESAISUnits
description: Describe your new bucket
icon: view_stream
primary: form
readOnly: false
history: false
properties:
  unit:
    type: relation
    title: unit
    description: Description of the unit input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6648c50dccaded002c60aa88
    dependent: false
    primary: serial_number
  form:
    type: string
    title: form
    description: Description of the form input
    options:
      position: bottom
  form_data:
    type: string
    title: form_data
    description: Description of the form_data input
    options:
      position: bottom
  status:
    type: array
    title: status
    description: Description of the status input
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
      enum:
        - exist
        - deleted
      default: exist
  is_sais_went_to:
    type: boolean
    title: is_sais_went_to
    description: Description of the is_sais_went_to input
    options:
      position: bottom
    default: false
  deficiencies_corrected:
    type: boolean
    title: deficiencies_corrected
    description: Description of the deficiencies_corrected input
    options:
      position: bottom
    default: false
acl:
  write: true==true
  read: true==true
order: 24
category: pages
