_id: 655f5ee3d71b6e002cf94752
title: Overtime
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  employee:
    type: relation
    title: employee
    description: Personel
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655cc987d71b6e002cf8b478
    dependent: false
    primary: name
  overtime:
    type: date
    title: overtime
    description: Tarih
    options:
      position: bottom
  start_time:
    type: date
    title: start_time
    description: Başlangıç Saati
    options:
      position: bottom
  end_time:
    type: date
    title: end_time
    description: Bitiş Saati
    options:
      position: bottom
  department_head_approval:
    type: boolean
    title: department_head_approval
    description: Bölüm Başkanı Onayı
    options:
      position: bottom
    default: false
  manager_approval:
    type: boolean
    title: manager_approval
    description: Yönetici Onayı
    options:
      position: bottom
    default: false
  reason:
    type: textarea
    title: reason
    description: Not
    options:
      position: bottom
  overtime_amount:
    type: number
    title: overtime_amount
    description: Description of the overtime_amount input
    options:
      position: bottom
    default: 0
  project:
    type: relation
    title: project
    description: Proje
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  product_index_from_order:
    type: number
    title: product_index_from_order
    description: Ünite
    options:
      position: bottom
  without_project:
    type: boolean
    title: without_project
    description: Projesiz
    options:
      position: bottom
    default: false
  job_description:
    type: string
    title: job_description
    description: İş Tanımı
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 21
category: pages
required:
  - employee
  - overtime
  - start_time
  - end_time
