_id: 655f5ee3d71b6e002cf94752
title: Overtime
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  employee:
    type: relation
    title: employee
    description: Personel
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655cc987d71b6e002cf8b478
    dependent: false
    primary: name
  overtime:
    type: date
    title: overtime
    description: Tarih
    options:
      position: bottom
  department_head_approval:
    type: boolean
    title: department_head_approval
    description: Bölüm Başkanı Onayı
    options:
      position: bottom
    default: false
  manager_approval:
    type: boolean
    title: manager_approval
    description: Yönetici Onayı
    options:
      position: bottom
    default: false
  reason:
    type: textarea
    title: reason
    description: Not
    options:
      position: bottom
  without_project:
    type: boolean
    title: without_project
    description: Projesiz
    options:
      position: bottom
    default: false
  job_description:
    type: string
    title: job_description
    description: İş Tanımı
    options:
      position: bottom
  unit:
    type: relation
    title: unit
    description: Ünite
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6648c50dccaded002c60aa88
    dependent: false
    primary: serial_number
  start_time:
    type: string
    title: start_time
    description: Description of the start_time input
    options:
      position: bottom
  end_time:
    type: string
    title: end_time
    description: Description of the end_time input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 12
category: pages
required:
  - employee
  - overtime
