_id: 6576ddbbd71b6e002cfb2812
title: FieldTeams
description: Describe your new bucket
icon: view_stream
primary: team_name
readOnly: false
history: false
properties:
  team_name:
    type: string
    title: team_name
    description: Ekip Adı
    options:
      position: bottom
  employees:
    type: array
    title: employees
    description: Kadro
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        employee:
          type: relation
          title: employee
          description: Personel
          options:
            position: bottom
          relationType: onetoone
          bucketId: 655cc987d71b6e002cf8b478
          dependent: false
        salary:
          type: number
          title: salary
          description: Maaş
          options:
            position: bottom
        minimum_wage:
          type: number
          title: minimum_wage
          description: Asgari Ücret
          options:
            position: bottom
        is_boss:
          type: boolean
          title: is_boss
          description: Patron
          options:
            position: bottom
          default: false
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 7
category: pages
required:
  - team_name
