_id: 65721d81d71b6e002cfaba28
title: Contracts
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  project:
    type: relation
    title: project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  agreement:
    type: array
    title: agreement
    description: Sözleşme Dosyası
    options:
      position: left
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  agreement_signed:
    type: array
    title: agreement_signed
    description: İmzalı Sözleşme Dosyası
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  payment:
    type: array
    title: payment
    description: Ödemeler
    options:
      position: right
    items:
      title: Title of the items
      type: object
      properties:
        method:
          type: string
          title: method
          description: Ödeme Şekli
          options:
            position: bottom
          enum:
            - döviz çeki
            - barter
        date:
          type: date
          title: date
          description: Ödeme Tarihi
          options:
            position: bottom
        money_amount:
          type: number
          title: money_amount
          description: Description of the money_amount input
          options:
            position: bottom
  status:
    type: string
    title: status
    description: |-
      Takipteki
      İmzalanan
      İmzalanmayan
    default: exist
    enum:
      - exist
      - deleted
      - signed
      - unsigned
    options:
      position: right
  delivery_time:
    type: string
    title: delivery_time
    description: Teslim Süresi
    options:
      position: bottom
  agreement_date:
    type: date
    title: agreement_date
    description: Sözleşme Tarihi
    options:
      position: bottom
  delivery_date:
    type: date
    title: delivery_date
    description: Description of the delivery_date input
    options:
      position: bottom
  estimated_arrival_date:
    type: date
    title: estimated_arrival_date
    description: Description of the estimated_arrival_date input
    options:
      position: bottom
  schindler_files:
    type: array
    title: schindler_files
    description: Description of the schindler_files input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  pull_signal_form:
    type: array
    title: pull_signal_form
    description: Description of the pull_signal_form input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  notes_for_assembly:
    type: textarea
    title: notes_for_assembly
    description: Description of the notes_for_assembly input
    options:
      position: bottom
  invoice:
    type: array
    title: invoice
    description: Description of the invoice input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  order_status:
    type: string
    title: order_status
    description: Description of the order_status input
    options:
      position: bottom
    enum:
      - waiting
      - approved
    default: waiting
  units_created:
    type: boolean
    title: units_created
    description: Description of the units_created input
    options:
      position: bottom
    default: false
  unit_worksite_delivery_form:
    type: array
    title: unit_worksite_delivery_form
    description: Description of the unit_worksite_delivery_form input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  unit_worksite_delivery_photos:
    type: array
    title: unit_worksite_delivery_photos
    description: Description of the unit_worksite_delivery_photos input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  mechanical_assembly_delivery_form:
    type: array
    title: mechanical_assembly_delivery_form
    description: Description of the mechanical_assembly_delivery_form input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  mechanical_assembly_delivery_photos:
    type: array
    title: mechanical_assembly_delivery_photos
    description: Description of the mechanical_assembly_delivery_photos input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  damage_notification_form:
    type: array
    title: damage_notification_form
    description: Description of the damage_notification_form input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  damage_notification_photos:
    type: array
    title: damage_notification_photos
    description: Description of the damage_notification_photos input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  external_files:
    type: array
    title: external_files
    description: Description of the external_files input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  extra_material:
    type: array
    title: extra_material
    description: Description of the extra_material input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        name:
          type: string
          title: name
          description: Description of the name input
          options:
            position: bottom
        count:
          type: number
          title: count
          description: Description of the count input
          options:
            position: bottom
acl:
  write: true==true
  read: true==true
order: 6
category: pages
required: []
