_id: 65721d81d71b6e002cfaba28
title: Contracts
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  project:
    type: relation
    title: project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  customer:
    type: relation
    title: customer
    description: Müşteri
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d309082063a002c6f9851
    dependent: false
    primary: name
  agreement:
    type: array
    title: agreement
    description: Sözleşme Dosyası
    options:
      position: left
    items:
      title: many
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  agreement_signed:
    type: array
    title: agreement_signed
    description: İmzalı Sözleşme Dosyası
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  payment:
    type: array
    title: payment
    description: Ödemeler
    options:
      position: right
    items:
      title: Title of the items
      type: object
      properties:
        method:
          type: string
          title: method
          description: Ödeme Şekli
          options:
            position: bottom
          enum:
            - döviz çeki
            - barter
        date:
          type: date
          title: date
          description: Ödeme Tarihi
          options:
            position: bottom
        money_amount:
          type: string
          title: money_amount
          description: Ödeme Tutarı
          options:
            position: bottom
  status:
    type: string
    title: status
    description: |-
      Takipteki
      İmzalanan
      İmzalanmayan
    default: exist
    enum:
      - exist
      - deleted
      - signed
      - unsigned
    options:
      position: right
  product_count:
    type: number
    title: product_count
    description: Ünite Adet
    options:
      position: bottom
  delivery_time:
    type: string
    title: delivery_time
    description: Teslim Süresi
    options:
      position: bottom
  agreement_date:
    type: date
    title: agreement_date
    description: Sözleşme Tarihi
    options:
      position: bottom
  offers:
    type: relation
    title: offers
    description: Description of the offers input
    options:
      position: bottom
    relationType: onetomany
    bucketId: 651d6a2882063a002c6f9ba3
    dependent: false
    primary: reference_number
acl:
  write: true==true
  read: true==true
order: 4
category: pages
required: []
