_id: 662f6f043931f4002bf666fb
title: AssignedTrainings
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  employees:
    type: relation
    title: employees
    description: Description of the employees input
    options:
      position: bottom
    relationType: onetomany
    bucketId: 655cc987d71b6e002cf8b478
    dependent: false
    primary: name
  training:
    type: relation
    title: training
    description: Eğitim
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655de02dd71b6e002cf8eab4
    dependent: false
    primary: name
  status:
    type: string
    title: status
    description: ""
    options:
      position: bottom
    enum:
      - exist
      - deleted
    default: exist
  date:
    type: date
    title: date
    description: Tarih
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 16
category: pages
