_id: 662f6f043931f4002bf666fb
title: AssignedTrainings
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  training:
    type: relation
    title: training
    description: Eğitim
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655de02dd71b6e002cf8eab4
    dependent: false
    primary: name
  employees:
    type: array
    title: employees
    description: Personeller
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        employee:
          type: relation
          title: employee
          description: ""
          options:
            position: bottom
          relationType: onetoone
          bucketId: 655cc987d71b6e002cf8b478
          dependent: false
  status:
    type: string
    title: status
    description: ""
    options:
      position: bottom
    enum:
      - exist
      - deleted
    default: exist
  date:
    type: date
    title: date
    description: Tarih
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 15
category: pages
