_id: 667d75d2a67577002b36b364
title: MapLocations
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  status:
    type: string
    title: status
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 32
category: pages
