_id: 653eafa8d71b6e002cf641e8
title: Table-Buttons
description: Describe your new bucket
icon: note_add
primary: title
readOnly: false
history: false
properties:
  bucket:
    type: relation
    title: bucket
    description: Description of the bucket input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6544bc6dd71b6e002cf6f476
    dependent: false
    primary: bucket_title
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
      unique: false
  header_name:
    type: string
    title: header_name
    description: Description of the header_name input
    options:
      position: bottom
  description:
    type: string
    title: description
    description: Description of the buttons
    options:
      position: bottom
  additional_properties:
    type: string
    title: additional_properties
    description: additional properties of button
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 30
required: []
category: config
