_id: 66a9f652627691002c88f5ae
title: MaintenanceMaintenance
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  status:
    type: string
    title: status
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: bottom
  maintenance_unit:
    type: relation
    title: maintenance_unit
    description: Description of the maintenance_unit input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6697d098082079002b1df695
    dependent: false
    primary: installation_number
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
  start_time:
    type: string
    title: start_time
    description: Description of the start_time input
    options:
      position: bottom
  end_time:
    type: string
    title: end_time
    description: Description of the end_time input
    options:
      position: bottom
  file:
    type: array
    title: file
    description: Description of the file input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  is_maintenaned:
    type: boolean
    title: is_maintenaned
    description: Description of the is_maintenaned input
    options:
      position: bottom
    default: false
  customer_did_not_request_maintenance:
    type: boolean
    title: customer_did_not_request_maintenance
    description: Description of the customer_did_not_request_maintenance input
    options:
      position: bottom
    default: false
  unit_is_down:
    type: boolean
    title: unit_is_down
    description: Description of the unit_is_down input
    options:
      position: bottom
    default: false
  photo:
    type: array
    title: photo
    description: Description of the photo input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  photo_position:
    type: string
    title: photo_position
    description: Description of the photo_position input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 29
category: pages
