_id: 651d6a2882063a002c6f9ba3
title: Offers
description: Teklifler
icon: view_stream
primary: reference_number
readOnly: false
history: false
properties:
  project:
    type: relation
    title: project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  reference_number:
    type: string
    title: reference_number
    description: Referans NO
    options:
      position: bottom
  notes:
    type: textarea
    title: notes
    description: Notlar
    options:
      position: bottom
  shape_screenshot:
    type: array
    title: shape_screenshot
    description: Shape Ekran Görüntüsü
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  shape_property_file:
    type: array
    title: shape_property_file
    description: Shape Özellik Dosyası
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  proposed_solution:
    type: array
    title: proposed_solution
    description: Teklif Dosyası
    options:
      position: right
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  status:
    type: string
    title: status
    description: |-
      Takipteki
      Onaylanan
      Onaylanmayan
      Beklemeye Alınan
    default: exist
    enum:
      - exist
      - deleted
      - confirmed
      - unapproved
      - pended
      - revised
    options:
      position: right
  created_date:
    type: date
    title: created_date
    description: Oluşturma Tarihi
    options:
      position: left
    default: :created_at
  offer_validity_period:
    type: date
    title: offer_validity_period
    description: Teklif Geçerlilik Süresi
    options:
      position: bottom
  products:
    type: array
    title: products
    description: Üniteler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        product:
          type: relation
          title: product
          description: Ünite
          options:
            position: bottom
          relationType: onetoone
          bucketId: 651d84bc82063a002c6f9f9a
          dependent: false
        docx_data:
          type: array
          title: docx_data
          description: Özellikler
          options:
            position: bottom
          items:
            title: Title of the items
            type: object
            properties:
              json_string:
                type: string
                title: json_string
                description: Description of the json_string input
                options:
                  position: bottom
              photo:
                type: array
                title: photo
                description: Description of the photo input
                options:
                  position: bottom
                items:
                  title: Title of the items
                  type: object
                  properties:
                    storage:
                      type: storage
                      title: storage
                      description: Description of the storage input
                      options:
                        position: bottom
                    deleted:
                      type: boolean
                      title: deleted
                      description: Description of the deleted input
                      options:
                        position: bottom
                      default: false
        count:
          type: number
          title: count
          description: Description of the count input
          options:
            position: bottom
  delivery_time:
    type: string
    title: delivery_time
    description: Teslim Süresi
    options:
      position: bottom
  birim:
    type: string
    title: birim
    description: Birim
    options:
      position: bottom
    enum:
      - $
      - ₺
      - €
  kdv:
    type: number
    title: kdv
    description: KDV
    options:
      position: bottom
    default: 16
  revised_offer:
    type: relation
    title: revised_offer
    description: Description of the revised_offer input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d6a2882063a002c6f9ba3
    dependent: false
    primary: reference_number
acl:
  write: true==true
  read: true==true
order: 3
category: pages
required: []
