_id: 6527f226ffa6b3002d10cc44
title: Notifications
description: Describe your new bucket
icon: notifications
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the description input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6527f268ffa6b3002d10cc50
    dependent: false
    primary: identifier
  seen:
    type: boolean
    title: seen
    description: Description of the seen input
    options:
      position: bottom
    default: false
  seen_date:
    type: date
    title: seen_date
    description: Description of the seen_date input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 35
