_id: 655f2fd0d71b6e002cf9186e
title: SAISProjects
description: Projeler
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  ordered_project:
    type: relation
    title: ordered_project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6527b072ffa6b3002d10bfd3
    dependent: false
    primary: name
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 25
category: pages
