_id: 651e842a82063a002c6fa24f
title: Projects
description: Projeler
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  customer:
    type: relation
    title: customer
    description: Müşteri Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d309082063a002c6f9851
    dependent: false
    primary: name
  name:
    type: string
    title: name
    description: Proje Adı
    options:
      position: bottom
      translate: false
  related_person:
    type: string
    title: related_person
    description: İlgili Kişi Adı
    options:
      position: bottom
  related_person_phone:
    type: string
    title: related_person_phone
    description: İlgili Kişi Telefonu
    options:
      position: bottom
  related_person_role:
    type: string
    title: related_person_role
    description: İlgili Kişi Görevi
    options:
      position: bottom
  related_person_email:
    type: string
    title: related_person_email
    description: İlgili Kişi E-Mail
    options:
      position: bottom
  building_drawing:
    type: array
    title: building_drawing
    description: Bina Çizimi
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        name:
          type: string
          title: name
          description: name
          options:
            position: bottom
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  field_control_form:
    type: array
    title: field_control_form
    description: Saha Ölçümü
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        name:
          type: string
          title: name
          description: name
          options:
            position: bottom
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  photos:
    type: array
    title: photos
    description: Fotoğraflar
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        name:
          type: string
          title: name
          description: name
          options:
            position: bottom
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  additional_document:
    type: array
    title: additional_document
    description: Ek Döküman
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        name:
          type: string
          title: name
          description: name
          options:
            position: bottom
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  comment_section:
    type: textarea
    title: comment_section
    description: Notlar
    options:
      position: bottom
  reminder:
    type: date
    title: reminder
    description: Hatırlatma
    options:
      position: bottom
  created_date:
    type: date
    title: created_date
    description: Oluşturma Tarihi
    options:
      position: left
    readOnly: false
    default: :created_at
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  map_locations:
    type: array
    title: map_locations
    description: Konum Bilgileri
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        location:
          type: string
          title: location
          description: ""
          options:
            position: bottom
  serial_number:
    type: string
    title: serial_number
    description: Description of the serial_number input
    options:
      position: bottom
  products:
    type: relation
    title: products
    description: Description of the products input
    options:
      position: bottom
    relationType: onetomany
    bucketId: 66aff3beee419a002c1f01c7
    dependent: false
    primary: count
  map_location:
    type: relation
    title: map_location
    description: Description of the map_location input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 667d75d2a67577002b36b364
    dependent: false
    primary: title
acl:
  write: true==true
  read: true==true
order: 2
required: []
category: pages
