_id: 65437ba6d71b6e002cf6cfdf
name: bucketsTriggers
language: javascript
timeout: 12
triggers:
  addStatusFieldToBucket:
    options:
      collection: buckets
      type: REPLACE
    type: database
    active: true
env: {}
memoryLimit: 100
order: 4
