_id: 655dea3ad71b6e002cf8eee1
title: Equipment
description: Ekipmanlar
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Adı
    options:
      position: bottom
  training:
    type: relation
    title: training
    description: Gerekli Eğitimin Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655de02dd71b6e002cf8eab4
    dependent: false
    primary: name
  status:
    type: string
    title: status
    description: |-
      -exist
      -deleted
      -archived
    default: exist
    enum:
      - exist
      - deleted
      - archived
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 17
category: pages
