_id: 655dde2ed71b6e002cf8e4a8
title: Employees-OHS
description: Personeller
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  employee:
    type: relation
    title: employee
    description: Çalışan
    options:
      position: bottom
    relationType: onetoone
    bucketId: 655cc987d71b6e002cf8b478
    dependent: false
    primary: name
  trainings:
    type: array
    title: trainings
    description: Eğitimler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        training:
          type: relation
          title: training
          description: Eğitim
          options:
            position: bottom
          relationType: onetoone
          bucketId: 655de02dd71b6e002cf8eab4
          dependent: false
        notes:
          type: textarea
          title: notes
          description: Not
          options:
            position: bottom
  cautions_and_punishments:
    type: array
    title: cautions_and_punishments
    description: Uyarılar ve Cezalar
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        date:
          type: date
          title: date
          description: Tarih
          options:
            position: bottom
        instructor:
          type: string
          title: instructor
          description: Uyarıyı veren kişi
          options:
            position: bottom
        notes:
          type: textarea
          title: notes
          description: Notlar
          options:
            position: bottom
        file:
          type: array
          title: file
          description: Dosya
          options:
            position: bottom
          items:
            title: Title of the items
            type: object
            properties:
              storage:
                type: storage
                title: storage
                description: Description of the storage input
                options:
                  position: bottom
              deleted:
                type: boolean
                title: deleted
                description: Description of the deleted input
                options:
                  position: bottom
                default: false
  equipments:
    type: array
    title: equipments
    description: Ekipmanlar
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        name:
          type: string
          title: name
          description: Adı
          options:
            position: bottom
        amount:
          type: number
          title: amount
          description: Adet
          options:
            position: bottom
acl:
  write: true==true
  read: true==true
order: 14
category: pages
required:
  - employee
