_id: 65782dabd71b6e002cfb5489
title: ProgressPayments
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  project_date:
    type: date
    title: project_date
    description: Proje Yılı
    options:
      position: bottom
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  project:
    type: relation
    title: project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  product_index_from_order:
    type: number
    title: product_index_from_order
    description: Ünite
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 10
category: pages
required: []
