_id: 657ae033d71b6e002cfbe32f
title: MonthlyProgressPayments
description: Describe your new bucket
icon: view_stream
primary: month
readOnly: false
history: false
properties:
  year:
    type: number
    title: year
    description: Yıl
    options:
      position: bottom
      unique: false
    enum:
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
      - 2029
      - 2030
      - 2031
      - 2032
      - 2033
      - 2034
      - 2035
      - 2036
      - 2037
      - 2038
      - 2039
      - 2040
  month:
    type: string
    title: month
    description: Ay
    options:
      position: bottom
    enum:
      - Ocak
      - Şubat
      - Mart
      - Nisan
      - Mayıs
      - Haziran
      - Temmuz
      - Ağustos
      - Eylül
      - Ekim
      - Kasım
      - Aralık
  team_name:
    type: relation
    title: team_name
    description: Ekip
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6576ddbbd71b6e002cfb2812
    dependent: false
    primary: team_name
  payments:
    type: array
    title: payments
    description: Ödemeler Tablosu
    options:
      position: bottom
    items:
      title: grid
      type: object
      properties:
        project:
          type: relation
          title: project
          description: Proje Adı
          options:
            position: bottom
          relationType: onetoone
          bucketId: 651e842a82063a002c6fa24f
          dependent: false
        work_status:
          type: string
          title: work_status
          description: İşin Durumu
          options:
            position: bottom
          enum:
            - MEK.MONTAJ
            - TEST
            - ARA ÖDEME
        price_per_floor:
          type: number
          title: price_per_floor
          description: Birim Fiyat
          options:
            position: bottom
        work_percentage:
          type: string
          title: work_percentage
          description: "%"
          options:
            position: bottom
          enum:
            - 0%
            - 5%
            - 10%
            - 15%
            - 20%
            - 25%
            - 30%
            - 35%
            - 40%
            - 45%
            - 50%
            - 55%
            - 60%
            - 65%
            - 70%
            - 75%
            - 80%
            - 85%
            - 90%
            - 95%
            - 100%
        date:
          type: date
          title: date
          description: Ödeme Tarihi
          options:
            position: bottom
        product_index_from_order:
          type: number
          title: product_index_from_order
          description: Ünite
          options:
            position: bottom
        fuel_price:
          type: number
          title: fuel_price
          description: Yakıt Litre Fiyatı
          options:
            position: bottom
        payed_fuel_cost:
          type: number
          title: payed_fuel_cost
          description: Ödenen Yakıt Ücreti
          options:
            position: bottom
        fuel_date:
          type: date
          title: fuel_date
          description: Yakıt Ödeme Tarihi
          options:
            position: bottom
        payment_no:
          type: number
          title: payment_no
          description: Ödeme No
          options:
            position: bottom
        payed_floor_cost:
          type: number
          title: payed_floor_cost
          description: Ödeme
          options:
            position: bottom
      required: []
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
      - paid
    options:
      position: right
  additional_payments:
    type: array
    title: additional_payments
    description: Ek Ödenecek İşler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        payment_amount:
          type: number
          title: payment_amount
          description: Tutar
          options:
            position: bottom
        reason:
          type: textarea
          title: reason
          description: Açıklama
          options:
            position: bottom
  advance_payment_and_other:
    type: array
    title: advance_payment_and_other
    description: Bu Aydan Verilen Avans Ve Diğer Ödemeler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        payment_amount:
          type: number
          title: payment_amount
          description: Tutar
          options:
            position: bottom
        reason:
          type: textarea
          title: reason
          description: Açıklama
          options:
            position: bottom
        currency:
          type: string
          title: currency
          description: Birim
          options:
            position: bottom
          enum:
            - ₺
            - €
            - $
            - £
          default: ₺
  dept_tl:
    type: object
    title: dept_tl
    description: Borç (TL)
    options:
      position: bottom
    properties:
      cut_this_month_tl:
        title: cut_this_month_tl
        description: Bu Ay Yapılan Kesinti (TL)
        type: number
      next_month_dept_tl:
        title: next_month_dept_tl
        description: Sonraki Aya Devreden Borç (TL)
        type: number
      previous_month_dept_tl:
        title: previous_month_dept_tl
        description: Önceki Aydan Devreden Avans Borcu (TL)
        type: number
      total_advance_payment_and_other_tl:
        title: total_advance_payment_and_other_tl
        description: Bu Aydan Verilen Avans Ve Diğer Ödemeler Toplamı (TL)
        type: number
      total_debt_tl:
        title: total_debt_tl
        description: Toplam Borç (TL)
        type: number
  dept_euro:
    type: object
    title: dept_euro
    description: Borç (€)
    options:
      position: bottom
    properties:
      cut_this_month_euro:
        title: cut_this_month_euro
        description: Bu Ay Yapılan Kesinti (€)
        type: number
      next_month_dept_euro:
        title: next_month_dept_euro
        description: Sonraki Aya Devreden Borç (€)
        type: number
      previous_month_dept_euro:
        title: previous_month_dept_euro
        description: Önceki Aydan Devreden Avans Borcu (€)
        type: number
      total_advance_payment_and_other_euro:
        title: total_advance_payment_and_other_euro
        description: Bu Aydan Verilen Avans Ve Diğer Ödemeler Toplamı (€)
        type: number
      total_debt_euro:
        title: total_debt_euro
        description: Toplam Borç (€)
        type: number
      euro_exchange_rate:
        title: euro_exchange_rate
        description: Euro Döviz Kuru
        type: number
      euro_equivalent_lira:
        title: euro_equivalent_lira
        description: TL Karşılığı
        type: number
  dept_dollar:
    type: object
    title: dept_dollar
    description: Borç ($)
    options:
      position: bottom
    properties:
      cut_this_month_dollar:
        title: cut_this_month_dollar
        description: Bu Ay Yapılan Kesinti ($)
        type: number
      next_month_dept_dollar:
        title: next_month_dept_dollar
        description: Sonraki Aya Devreden Borç ($)
        type: number
      previous_month_dept_dollar:
        title: previous_month_dept_dollar
        description: Önceki Aydan Devreden Avans Borcu ($)
        type: number
      total_advance_payment_and_other_dollar:
        title: total_advance_payment_and_other_dollar
        description: Bu Aydan Verilen Avans Ve Diğer Ödemeler Toplamı ($)
        type: number
      total_debt_dollar:
        title: total_debt_dollar
        description: Toplam Borç ($)
        type: number
      dollar_exchange_rate:
        title: dollar_exchange_rate
        description: Dolar Döviz Kuru
        type: number
      dollar_equivalent_lira:
        title: dollar_equivalent_lira
        description: TL Karşılığı
        type: number
  dept_sterling:
    type: object
    title: dept_sterling
    description: Borç (£)
    options:
      position: bottom
    properties:
      cut_this_month_sterling:
        title: cut_this_month_sterling
        description: Bu Ay Yapılan Kesinti (£)
        type: number
      next_month_dept_sterling:
        title: next_month_dept_sterling
        description: Sonraki Aya Devreden Borç (£)
        type: number
      previous_month_dept_sterling:
        title: previous_month_dept_sterling
        description: Önceki Aydan Devreden Avans Borcu (£)
        type: number
      total_advance_payment_and_other_sterling:
        title: total_advance_payment_and_other_sterling
        description: Bu Aydan Verilen Avans Ve Diğer Ödemeler Toplamı (£)
        type: number
      total_debt_sterling:
        title: total_debt_sterling
        description: Toplam Borç (£)
        type: number
      sterling_exchange_rate:
        title: sterling_exchange_rate
        description: Sterlin Döviz Kuru
        type: number
      sterling_equivalent_lira:
        title: sterling_equivalent_lira
        description: TL Karşılığı
        type: number
  salary:
    type: array
    title: salary
    description: Maaş Ödemeleri
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        employee:
          type: relation
          title: employee
          description: Personel
          options:
            position: bottom
          relationType: onetoone
          bucketId: 655cc987d71b6e002cf8b478
          dependent: false
        salary_amount:
          type: number
          title: salary_amount
          description: Ödemeler Toplamı
          options:
            position: bottom
        minimum_wage:
          type: number
          title: minimum_wage
          description: Halk Banka Yatan Maaş Ödeme
          options:
            position: bottom
        extra_salary:
          type: number
          title: extra_salary
          description: Garanti Banka Yatan Ödeme
          options:
            position: bottom
        minimum_wage_date:
          type: date
          title: minimum_wage_date
          description: Halk Banka Yatan Maaş Ödeme Tarihi
          options:
            position: bottom
        extra_salary_date:
          type: date
          title: extra_salary_date
          description: Garanti Banka Yatan Maaş Ödeme
          options:
            position: bottom
        minimum_wage_receipt:
          type: string
          title: minimum_wage_receipt
          description: Halk Banka Yatan Maaş Ödeme Dekont No
          options:
            position: bottom
        extra_salary_receipt:
          type: string
          title: extra_salary_receipt
          description: Garanti Banka Yatan Ödeme Dekont No
          options:
            position: bottom
        minimum_wage_receipt_file:
          type: array
          title: minimum_wage_receipt_file
          description: Halk Banka Yatan Maaş Ödeme Dekont
          options:
            position: bottom
          items:
            title: Title of the items
            type: object
            properties:
              storage:
                type: storage
                title: storage
                description: Description of the storage input
                options:
                  position: bottom
              deleted:
                type: boolean
                title: deleted
                description: Description of the deleted input
                options:
                  position: bottom
                default: false
        extra_salary_receipt_file:
          type: array
          title: extra_salary_receipt_file
          description: Garanti Banka Yatan Ödeme Dekont
          options:
            position: bottom
          items:
            title: Title of the items
            type: object
            properties:
              storage:
                type: storage
                title: storage
                description: Description of the storage input
                options:
                  position: bottom
              deleted:
                type: boolean
                title: deleted
                description: Description of the deleted input
                options:
                  position: bottom
                default: false
acl:
  write: true==true
  read: true==true
order: 11
category: pages
required: []
