_id: 657ae033d71b6e002cfbe32f
title: MonthlyProgressPayments
description: Describe your new bucket
icon: view_stream
primary: month
readOnly: false
history: false
properties:
  year:
    type: number
    title: year
    description: Yıl
    options:
      position: bottom
      unique: false
    enum:
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
      - 2029
      - 2030
      - 2031
      - 2032
      - 2033
      - 2034
      - 2035
      - 2036
      - 2037
      - 2038
      - 2039
      - 2040
  month:
    type: string
    title: month
    description: Ay
    options:
      position: bottom
    enum:
      - Ocak
      - Şubat
      - Mart
      - Nisan
      - Mayıs
      - Haziran
      - Temmuz
      - Ağustos
      - Eylül
      - Ekim
      - Kasım
      - Aralık
  team_name:
    type: relation
    title: team_name
    description: Ekip
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6576ddbbd71b6e002cfb2812
    dependent: false
    primary: team_name
  payments:
    type: array
    title: payments
    description: Ödemeler Tablosu
    options:
      position: bottom
    items:
      title: grid
      type: object
      properties:
        project:
          type: relation
          title: project
          description: Proje Adı
          options:
            position: bottom
          relationType: onetoone
          bucketId: 651e842a82063a002c6fa24f
          dependent: false
        work_status:
          type: string
          title: work_status
          description: İşin Durumu
          options:
            position: bottom
          enum:
            - MEK.MONTAJ
            - TEST
            - ARA ÖDEME
        price_per_floor:
          type: number
          title: price_per_floor
          description: Birim Fiyat
          options:
            position: bottom
        work_percentage:
          type: string
          title: work_percentage
          description: "%"
          options:
            position: bottom
          enum:
            - 0%
            - 5%
            - 10%
            - 15%
            - 20%
            - 25%
            - 30%
            - 35%
            - 40%
            - 45%
            - 50%
            - 55%
            - 60%
            - 65%
            - 70%
            - 75%
            - 80%
            - 85%
            - 90%
            - 95%
            - 100%
        date:
          type: date
          title: date
          description: Ödeme Tarihi
          options:
            position: bottom
        product_index_from_order:
          type: number
          title: product_index_from_order
          description: Ünite
          options:
            position: bottom
        fuel_price:
          type: number
          title: fuel_price
          description: Yakıt Litre Fiyatı
          options:
            position: bottom
        payed_fuel_cost:
          type: number
          title: payed_fuel_cost
          description: Ödenen Yakıt Ücreti
          options:
            position: bottom
        fuel_date:
          type: date
          title: fuel_date
          description: Yakıt Ödeme Tarihi
          options:
            position: bottom
        payment_no:
          type: number
          title: payment_no
          description: Ödeme No
          options:
            position: bottom
        payed_floor_cost:
          type: number
          title: payed_floor_cost
          description: Ödeme
          options:
            position: bottom
      required: []
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  additional_payments:
    type: array
    title: additional_payments
    description: Ek Ödenecek İşler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        payment_amount:
          type: number
          title: payment_amount
          description: Tutar
          options:
            position: bottom
        reason:
          type: textarea
          title: reason
          description: Açıklama
          options:
            position: bottom
  advance_payment_and_other:
    type: array
    title: advance_payment_and_other
    description: Bu Aydan Verilen Avans Ve Diğer Ödemeler
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        payment_amount:
          type: number
          title: payment_amount
          description: Tutar
          options:
            position: bottom
        reason:
          type: textarea
          title: reason
          description: Açıklama
          options:
            position: bottom
        currency:
          type: string
          title: currency
          description: Birim
          options:
            position: bottom
          enum:
            - ₺
            - €
            - $
            - £
          default: ₺
  dept_tl:
    type: object
    title: dept_tl
    description: Borç (TL)
    options:
      position: bottom
  dept_euro:
    type: object
    title: dept_euro
    description: Borç (€)
    options:
      position: bottom
  dept_dollar:
    type: object
    title: dept_dollar
    description: Borç ($)
    options:
      position: bottom
  dept_sterling:
    type: object
    title: dept_sterling
    description: Borç (£)
    options:
      position: bottom
  salary:
    type: array
    title: salary
    description: Maaş Ödemeleri
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        employee:
          type: relation
          title: employee
          description: Personel
          options:
            position: bottom
          relationType: onetoone
          bucketId: 655cc987d71b6e002cf8b478
          dependent: false
acl:
  write: true==true
  read: true==true
order: 11
category: pages
required: []
