_id: 6560b7ccd71b6e002cf9654c
title: OrderTrackingProjects
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  ordered_project:
    type: relation
    title: ordered_project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6527b072ffa6b3002d10bfd3
    dependent: false
    primary: name
  emo:
    type: array
    title: emo
    description: EMO
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  mmo:
    type: array
    title: mmo
    description: MMO
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  working_space:
    type: array
    title: working_space
    description: Çalışma Dairesi İzni
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  preproduction_permit:
    type: array
    title: preproduction_permit
    description: Ön İzin
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  assembly_permit:
    type: array
    title: assembly_permit
    description: Montaj izni
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  corporation_permit:
    type: array
    title: corporation_permit
    description: İşletme izni
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 24
category: pages
