_id: 66aff3beee419a002c1f01c7
title: Projects___products
description: Describe your new bucket
icon: view_stream
primary: count
readOnly: false
history: false
properties:
  product:
    type: relation
    title: product
    description: Description of the product input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d84bc82063a002c6f9f9a
    dependent: false
    primary: model
  count:
    type: number
    title: count
    description: Description of the count input
    options:
      position: bottom
  status:
    type: string
    title: status
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 3
category: pages
