_id: 655f30f3d71b6e002cf91da0
title: TallySheet
description: Puantaj
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: bottom
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: bottom
  status:
    type: string
    title: status
    description: |-
      -exist
      -deleted
      -archived
    default: exist
    enum:
      - exist
      - deleted
      - archived
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 21
category: pages
