_id: 656ed054d71b6e002cfa47f0
title: FieldInspections
description: Describe your new bucket
icon: view_stream
primary: status
readOnly: false
history: false
properties:
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  created_date:
    type: date
    title: created_date
    description: Description of the created_date input
    options:
      position: bottom
    default: :created_at
  unit:
    type: relation
    title: unit
    description: Ünite
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6648c50dccaded002c60aa88
    dependent: false
    primary: serial_number
  content:
    type: string
    title: content
    description: Description of the content input
    options:
      position: bottom
  email_sender:
    type: relation
    title: email_sender
    description: Description of the email_sender input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6527f268ffa6b3002d10cc50
    dependent: false
    primary: identifier
acl:
  write: true==true
  read: true==true
order: 8
category: pages
required: []
