_id: 656ee1c2d71b6e002cfa505c
title: Info
description: Describe your new bucket
icon: info
primary: key
readOnly: false
history: false
properties:
  key:
    type: string
    title: key
    description: Description of the key input
    options:
      position: bottom
  value:
    type: number
    title: value
    description: Description of the value input
    options:
      position: bottom
  obj_test:
    type: object
    title: obj_test
    description: Description of the obj_test input
    options:
      position: bottom
    properties:
      storage:
        type: storage
        title: storage
        description: Description of the storage input
        options:
          position: bottom
      str:
        type: string
        title: str
        description: Description of the str input
        options:
          position: right
acl:
  write: true==true
  read: true==true
order: 35
