_id: 6544bc6dd71b6e002cf6f476
title: Pages
description: Describe your new bucket
icon: list_alt
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Description of the title input
    options:
      position: bottom
  description:
    type: string
    title: description
    description: Description of the description input
    options:
      position: bottom
  order:
    type: number
    title: order
    description: Description of the order input
    options:
      position: bottom
  type:
    type: string
    title: type
    description: Description of the type input
    options:
      position: bottom
    enum:
      - table
      - ganttChart
      - custom
      - customFormData
    default: table
  field_features:
    type: array
    title: field_features
    description: Field features and view options
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        width:
          type: number
          title: width
          description: width in pixels
          options:
            position: bottom
          default: 200
        order:
          type: number
          title: order
          description: order of field
          options:
            position: bottom
          default: 0
        field_name:
          type: string
          title: field_name
          description: name of field
          options:
            position: bottom
        prevent_adding_and_removing_elements_to_an_array:
          type: boolean
          title: prevent_adding_and_removing_elements_to_an_array
          description: turn to true for prevent adding and removing elements to an array
          options:
            position: bottom
          default: false
        hide_from_table:
          type: boolean
          title: hide_from_table
          description: set to true to hide a column from the table
          options:
            position: bottom
          default: false
        hide_from_form_data:
          type: boolean
          title: hide_from_form_data
          description: set to true to hide a field from the formData
          options:
            position: bottom
          default: false
        read_only:
          type: boolean
          title: read_only
          description: set true to set the property to read-only
          options:
            position: bottom
          default: false
        date_only:
          type: boolean
          title: date_only
          description: turn true to allow date only selection
          options:
            position: bottom
          default: false
        time_only:
          type: boolean
          title: time_only
          description: turn true to allow time only selection
          options:
            position: bottom
          default: false
        slider:
          type: boolean
          title: slider
          description: if field type is string turn true to show slider instead of input
            box. Slider can set values in the range from 0 to 100
          options:
            position: bottom
          default: false
        hide_from_detail_page:
          type: boolean
          title: hide_from_detail_page
          description: set to true to hide a column from the detailPage
          options:
            position: bottom
          default: false
        disable_editing:
          type: boolean
          title: disable_editing
          description: set to true to disable editing this field after creation (if field
            type is array then this disables remove button)
          options:
            position: bottom
          default: false
        grid_width:
          type: number
          title: grid_width
          description: width in fr for formData (max line width is 12)
          options:
            position: bottom
          default: 6
        support:
          type: string
          title: support
          description: the demonstrative field needs support (relation field) from which
            it will receive data
          options:
            position: bottom
  internal_field_features:
    type: array
    title: internal_field_features
    description: "Features and view options of internal fields (object array properties) "
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        field_name:
          type: string
          title: field_name
          description: Description of the field_name input
          options:
            position: bottom
        date_only:
          type: boolean
          title: date_only
          description: turn true to allow date only selection
          options:
            position: bottom
          default: false
        read_only:
          type: boolean
          title: read_only
          description: set true to set the property to read-only
          options:
            position: bottom
          default: false
        time_only:
          type: boolean
          title: time_only
          description: turn true to allow time only selection
          options:
            position: bottom
          default: false
        order:
          type: number
          title: order
          description: order of field
          options:
            position: bottom
        disable_editing:
          type: boolean
          title: disable_editing
          description: set to true to disable editing this field
          options:
            position: bottom
          default: false
        grid_width:
          type: number
          title: grid_width
          description: width in fr for formData (max line width is 12)
          options:
            position: bottom
          default: 6
        hide_from_form_data:
          type: boolean
          title: hide_from_form_data
          description: set to true to hide a field from the formData
          options:
            position: bottom
          default: false
        hide_from_detail_page:
          type: boolean
          title: hide_from_detail_page
          description: set to true to hide a column from the detailPage
          options:
            position: bottom
          default: false
  page_features:
    type: array
    title: page_features
    description: >-
      no_new_button: removes the create button

      no_remove_button: removes the delete button

      cancel_movement_between_sections: removes the button to move between sections

      cancel_movement_between_sections_during_creation: cancels movement between sections while creating a new object
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
acl:
  write: true==true
  read: true==true
order: 33
category: config
