_id: 6527b072ffa6b3002d10bfd3
title: Orders
description: Siparişler
icon: view_stream
primary: notes_for_assembly
readOnly: false
history: false
properties:
  customer:
    type: relation
    title: customer
    description: Müşteri Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d309082063a002c6f9851
    dependent: false
    primary: name
  project:
    type: relation
    title: project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  delivery_date:
    type: date
    title: delivery_date
    description: Fabrika Çıkış Tarihi
    options:
      position: bottom
  estimated_arrival_date:
    type: date
    title: estimated_arrival_date
    description: Tahmini Gümrüğe Geliş Tarihi
    options:
      position: bottom
  schindler_files:
    type: array
    title: schindler_files
    description: Schindler dosyaları
    options:
      position: bottom
    items:
      title: many
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  pull_signal_form:
    type: array
    title: pull_signal_form
    description: Pull Signal Formu
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: array
          title: storage
          description: Description of the storage input
          options:
            position: bottom
          items:
            title: Title of the items
            type: string
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  notes_for_assembly:
    type: textarea
    title: notes_for_assembly
    description: Müşteri İsteği
    options:
      position: bottom
  invoice:
    type: array
    title: invoice
    description: Fatura
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  product_serial_number:
    type: array
    title: product_serial_number
    description: Ünite Seri Numara
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        serial_number:
          type: string
          title: serial_number
          description: Ünite Seri Numara
          options:
            position: bottom
        added_to_gantt_chart:
          type: boolean
          title: added_to_gantt_chart
          description: Montaj Planına Eklendi
          options:
            position: bottom
          default: false
        product:
          type: relation
          title: product
          description: Ünite
          options:
            position: bottom
          relationType: onetoone
          bucketId: 651d84bc82063a002c6f9f9a
          dependent: false
        offer:
          type: relation
          title: offer
          description: Description of the offer input
          options:
            position: bottom
          relationType: onetoone
          bucketId: 651d6a2882063a002c6f9ba3
          dependent: false
        product_index:
          type: number
          title: product_index
          description: Description of the product_index input
          options:
            position: bottom
        row_index:
          type: number
          title: row_index
          description: Description of the row_index input
          options:
            position: bottom
        unit_index:
          type: number
          title: unit_index
          description: Description of the unit_index input
          options:
            position: bottom
acl:
  write: true==true
  read: true==true
order: 5
category: pages
required: []
