_id: 66b4d593e6d086002c5dbeda
name: contracts
language: javascript
timeout: 12
triggers:
  getAvailableProjects:
    type: http
    active: true
    options:
      method: Get
      path: /offers/contracts
      preflight: true
env: {}
memoryLimit: 100
order: 1
category: pages
