_id: 6543b8d1d71b6e002cf6e30b
title: Additional-Relative-Fields
description: Describe your new bucket
icon: new_releases
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
    default: default_title
  bucket:
    type: relation
    title: bucket
    description: Description of the bucket input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6544bc6dd71b6e002cf6f476
    dependent: false
    primary: title
  related_bucket:
    type: relation
    title: related_bucket
    description: Description of the related_bucket input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6544bc6dd71b6e002cf6f476
    dependent: false
    primary: title
acl:
  write: true==true
  read: true==true
order: 32
category: config
