_id: 65489afcd71b6e002cf7406c
title: GanttChart
description: Yıllık Montaj Planı
icon: view_stream
primary: type
readOnly: false
history: false
properties:
  field_team:
    type: relation
    title: field_team
    description: Ekip
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6576ddbbd71b6e002cfb2812
    dependent: false
    primary: team_name
  customer:
    type: relation
    title: customer
    description: Müşteri
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651d309082063a002c6f9851
    dependent: false
    primary: name
  project_name:
    type: relation
    title: project_name
    description: Proje
    options:
      position: bottom
    relationType: onetoone
    bucketId: 651e842a82063a002c6fa24f
    dependent: false
    primary: name
  product_index_from_order:
    type: number
    title: product_index_from_order
    description: Ünite
    options:
      position: bottom
  start:
    type: date
    title: start
    description: Başlangıç Tarihi
    options:
      position: bottom
    default: :created_at
  type:
    type: string
    title: type
    description: Description of the type input
    options:
      position: right
    enum:
      - project
      - task
    default: project
  end:
    type: date
    title: end
    description: Bitiş Tarihi
    options:
      position: bottom
    default: :created_at
  progress:
    type: string
    title: progress
    description: İlerleme
    options:
      position: bottom
    default: "0"
  order:
    type: number
    title: order
    description: Description of the order input
    options:
      position: right
    default: 0
  project:
    type: string
    title: project
    description: Description of the project input
    options:
      position: right
  dependencies:
    type: array
    title: dependencies
    description: Description of the dependencies input
    options:
      position: right
    items:
      title: Title of the items
      type: string
  status:
    type: string
    title: status
    description: ""
    default: exist
    enum:
      - exist
      - deleted
    options:
      position: right
  amount_of_days:
    type: number
    title: amount_of_days
    description: Gün Sayısı
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 7
category: pages
required: []
