_id: 656dcec7d71b6e002cfa1b15
title: AssemblyProjects
description: Describe your new bucket
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Name
    options:
      position: right
  unit_worksite_delivery_form:
    type: array
    title: unit_worksite_delivery_form
    description: Ünite Şantiye Teslim Formu
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  ordered_project:
    type: relation
    title: ordered_project
    description: Proje Adı
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6527b072ffa6b3002d10bfd3
    dependent: false
    primary: name
  unit_worksite_delivery_photos:
    type: array
    title: unit_worksite_delivery_photos
    description: Ünite Şantiye Teslim Fotoğraflar
    options:
      position: bottom
    items:
      title: img
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  mechanical_assembly_delivery_form:
    type: array
    title: mechanical_assembly_delivery_form
    description: Mekanik Montaj Teslim Formu
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  mechanical_assembly_delivery_photos:
    type: array
    title: mechanical_assembly_delivery_photos
    description: Mekanik Montaj Teslim Fotoğraflar
    options:
      position: bottom
    items:
      title: img
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  damage_notification_form:
    type: array
    title: damage_notification_form
    description: Hasar Bildirim Formu
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: ""
  damage_notification_photos:
    type: array
    title: damage_notification_photos
    description: Hasar Bildirim Fotoğraflar
    options:
      position: bottom
    items:
      title: img
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  external_files:
    type: array
    title: external_files
    description: Harici Belgeler
    options:
      position: bottom
    items:
      title: ""
      type: object
      properties:
        storage:
          type: storage
          title: storage
          description: Description of the storage input
          options:
            position: bottom
        deleted:
          type: boolean
          title: deleted
          description: Description of the deleted input
          options:
            position: bottom
          default: false
      description: many
  extra_material:
    type: array
    title: extra_material
    description: Ekstra Malzeme
    options:
      position: bottom
    items:
      title: flex
      type: object
      properties:
        name:
          type: string
          title: name
          description: Adı
          options:
            position: bottom
        count:
          type: number
          title: count
          description: Adet
          options:
            position: bottom
  status:
    type: string
    title: status
    description: |-
      -exist
      -deleted
      -archived
    default: exist
    enum:
      - exist
      - deleted
      - archived
    options:
      position: right
acl:
  write: true==true
  read: true==true
order: 6
category: pages
required:
  - ordered_project
